Mo/3.1.0 support
HorizenOfficial/insight-api-zen pull request #15
Opened 2022-03-18 14:13 UTC by MarcoOl94

Added support for zend version 3.1.0 and removed sidechain LRU cache.

2022-03-18 14:19 UTC, cronicc requested changes

2022-03-18 14:19 UTC, cronicc commented on lib/sidechain.js
> +        return "Sidechain ID not found!"
Make this response JSON to not break parsers on the consumer side. e.g. `{"error": "Sidechain ID not found!"}`

2022-03-18 14:26 UTC, MarcoOl94 commented on lib/sidechain.js
> +        return "Sidechain ID not found!"
Done, thanks!

2022-03-18 14:29 UTC, cronicc approved these changes

2022-03-18 14:45 UTC, otoumas reviewed
See comments

2022-03-18 14:45 UTC, otoumas commented on lib/sidechain.js
> +    var to = parseInt(req.query.to) ? parseInt(req.query.to) : SidechainController.MAXIMUM_SIDECHAIN_SIZE;
How does this parseInt behave? I think that parseInt returns NaN which is not undefined or false. Maybe instead of trying to parse it could check that is a number first using isNum():
```
var from = isNum(req.query.from) ? parseInt(req.query.from) : 0;
var to = isNum(req.query.to) ? parseInt(req.query.to) : SidechainController.MAXIMUM_SIDECHAIN_SIZE;
```

2022-03-18 15:26 UTC, MarcoOl94 commented on lib/sidechain.js
> +    var to = parseInt(req.query.to) ? parseInt(req.query.to) : SidechainController.MAXIMUM_SIDECHAIN_SIZE;
Yes good catch, thanks!

2022-03-28 14:38 UTC, cronicc commented on lib/sidechain.js
> +    var to = parseInt(req.query.to) ? parseInt(req.query.to) : SidechainController.MAXIMUM_SIDECHAIN_SIZE;
Addressed in https://github.com/HorizenOfficial/insight-api-zen/pull/15/commits/81677d86afa55d3699e9d0b690080556bb59983b

2022-03-28 14:39 UTC, cronicc approved these changes

2022-03-28 14:39 UTC, merged